# Generated by Django 4.1.6 on 2023-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_orderdish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='name',
            field=models.CharField(blank=True, default='dish name', max_length=200, null=True),
        ),
    ]
