# Generated by Django 4.1.6 on 2023-02-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_orderdish_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdish',
            name='name',
        ),
    ]
