# Generated by Django 4.1.6 on 2023-02-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_orderdish_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdish',
            name='price',
        ),
    ]
