# Generated by Django 4.1.6 on 2023-02-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order_totalprice_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.table'),
        ),
    ]
