# Generated by Django 4.1.6 on 2023-02-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isBrought',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isDone',
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.table'),
        ),
    ]
