# Generated by Django 4.1.6 on 2023-02-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_order_isbrought_remove_order_isdone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isBrought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
