# Generated by Django 4.1.3 on 2023-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tableNumber',
            field=models.IntegerField(null=True),
        ),
    ]
