# Generated by Django 4.1.5 on 2023-07-04 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0012_alter_table_tablenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='isActive',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('BARTENDER', 'Bartender'), ('WAITER', 'Waiter'), ('WAITRESS', 'Waitress'), ('RESTAURANT_MANAGER', 'Restaurant Manager'), ('COOK', 'Cook')], default='BARTENDER', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
