# Generated by Django 4.1.5 on 2023-07-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_employee_isactive_dishcategory_colour_and_more'),
    ]

    operations = [
       migrations.AddField(
            model_name='dishcategory',
            name='colour',
            field=models.CharField(default='white', max_length=200),
        ),
    ]
