# Generated by Django 4.1.5 on 2023-07-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_dishcategory_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishcategory',
            old_name='colour',
            new_name='color',
        ),
    ]
