# Generated by Django 4.1.5 on 2023-07-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_position_alter_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishcategory',
            old_name='color',
            new_name='colour',
        ),
    ]
