# Generated by Django 4.1.5 on 2023-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_employee_iscashier_employee_isdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
