# Generated by Django 4.1.5 on 2023-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_order_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
        migrations.AddField(
            model_name='order',
            name='roomName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
