export const DISH_LIST_REQUEST = "DISH_LIST_REQUEST";
export const DISH_LIST_SUCCESS = "DISH_LIST_SUCCESS";
export const DISH_LIST_FAIL = "DISH_LIST_FAIL";

export const ORDER_DISH_LIST_REQUEST = "ORDER_DISH_LIST_REQUEST";
export const ORDER_DISH_LIST_SUCCESS = "ORDER_DISH_LIST_SUCCESS";
export const ORDER_DISH_LIST_FAIL = "ORDER_DISH_LIST_FAIL";

export const ADD_DISH_TO_MENU_REQUEST = "ADD_DISH_TO_MENU_REQUEST";
export const ADD_DISH_TO_MENU_SUCCESS = "ADD_DISH_TO_MENU_SUCCESS";
export const ADD_DISH_TO_MENU_FAIL = "ADD_DISH_TO_MENU_FAIL";

export const ADD_DISH_TO_MENU = "ADD_DISH_TO_MENU";

export const REMOVE_DISH_FROM_MENU = "REMOVE_DISH_FROM_MENU";
export const REMOVE_DISH_FROM_MENU_FAIL = "REMOVE_DISH_FROM_MENU_FAIL";
