export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAIL = "CREATE_ROOM_FAIL";

export const REMOVE_ROOM_SUCCESS = "REMOVE_ROOM_SUCCESS";
export const REMOVE_ROOM_REQUEST = "REMOVE_ROOM_REQUEST";
export const REMOVE_ROOM_FAIL = "REMOVE_ROOM_FAIL";
